services:
  mc:
    image: itzg/minecraft-server
    environment:
      INIT_MEMORYY: 1G
      MAX_MEMORY: 2G
      EULA: "true"
      TYPE: "PAPER"
      OPS: "ConciseCoast40"
      WHITELIST: |
        ConciseCoast40
        IsaacFinance
        GandalfTheBlack
      
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
      - ./plugins:/data/plugins
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}
  plugins: {}

